"""Turn the prototype into Shopify theme files (Phase 2): the room as the first section of the homepage.

    python3 azur/tools/build_theme.py        -> azur/theme/ (theme files) + azur/theme/files.json (renders for Content > Files)

The theme files are pushed into the draft theme "Azur Zimmer (Entwurf)" through the Admin API (themeFilesUpsert);
the renders go to Shopify Files (fileCreate, Shopify fetches them from this public repo). Nothing touches the live theme.

What changes against the prototype:
- one script bundle (config, then window.AZUR_SETUP from the section: products, URLs, JSON; then the rest; no Regie panel)
- the CSS is scoped to the room and its overlays (the theme keeps its own tokens, base styles and square corners)
- renders live in Files under flat names: assets/scene3/views/rail/lo/sky.webp -> azr2-views-rail-lo-sky.webp
- jersey models (GLB) for the 3D product view go to Files too; the magazine pages can be section blocks
- views.json / passes.json / a slim moves.json are printed into the page (snippets/azur-room-data.liquid)
- fonts: Archivo comes from the theme; Martian Mono and Caveat are self-hosted (no Google Fonts request)
"""
import json, os, re, shutil, subprocess, sys, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
REPO = os.path.dirname(ROOT)
SRC = os.path.join(ROOT, 'prototype')
PUB = os.path.join(ROOT, '.cache', 'publish')          # tools/build_artifact.py output (move strips)
OUT = os.path.join(ROOT, 'theme')
PREFIX = 'azr2-'                                        # bumped when the renders change (Files are cached); azr2 = round 3
SET = os.environ.get('AZUR_SET', 'scene3')
BRANCH = 'claude/shopify-notification-signup-o5avym'
RAW = f'https://raw.githubusercontent.com/emirharun07-hash/S-per-Lig-Fantasy-Manager/{BRANCH}/'
BUNDLE = ['azur-config.js', None, 'azur-light.js', 'azur-compositor.js', 'azur-rail.js', 'azur-drop.js', 'azur-viewer.js', 'azur-shop.js', 'azur-mag.js', 'azur-app.js']
SCOPE = ['.azur', '.azur-mag', '.azur-pdp', '.azur-holo', '.azur-ghost']   # the room and the overlays it appends to <body>


def files_name(path):
    """'assets/scene3/views/rail/lo/sky.webp' -> 'azr2-views-rail-lo-sky.webp' (same rule as urlMap in the section)."""
    p = re.sub(r'^assets/(scene\d/)?', '', path)
    return PREFIX + p.replace('@', '-at-').replace('/', '-')


def write(rel, text):
    dst = os.path.join(OUT, rel); os.makedirs(os.path.dirname(dst), exist_ok=True)
    open(dst, 'w').write(text)


def build_js():
    parts = []
    for f in BUNDLE:
        if f is None:
            parts.append('/* shop data, URLs and JSON from sections/azur-room.liquid */\nif (window.AZUR_SETUP) window.AZUR_SETUP(window.AZUR);\n')
        else:
            parts.append(f'/* ---- {f} ---- */\n' + open(os.path.join(SRC, 'js', f)).read())
    write('assets/azur-room.js', '/* AZUR room (generated by azur/tools/build_theme.py from azur/prototype/js; edit there). */\n' + '\n'.join(parts))


def build_css():
    css = open(os.path.join(SRC, 'css', 'azur-room.css')).read()
    scope = ', '.join(SCOPE)
    css = css.replace(':root {', scope + ' {', 1)
    css = re.sub(r'^html, body \{[^}]*\}\n', '', css, flags=re.M)
    css = re.sub(r'^body \{[^}]*\}\n', '', css, flags=re.M)
    # base rules keep their low weight inside the scope (:where adds none), so component classes still win
    where = ':where(' + scope + ')'
    css = re.sub(r'^\[hidden\] \{([^}]*)\}', lambda m: where + ' [hidden] {' + m.group(1) + '}', css, flags=re.M)
    css = re.sub(r'^button \{([^}]*)\}', lambda m: where + ' button {' + m.group(1) + '}', css, flags=re.M)
    css = re.sub(r'^:focus-visible \{([^}]*)\}', lambda m: where + ' :focus-visible {' + m.group(1) + '}', css, flags=re.M)
    # the room is the first section of the homepage, under the theme header (like the theme's campaign hero)
    css = css.replace('.azur { position: fixed; inset: 0; overflow: hidden; background: #0b0b0c; }',
                      '.azur { position: relative; isolation: isolate; height: calc(100vh - var(--bar-h, 0px)); height: calc(100svh - var(--bar-h, 0px));\n'
                      '  min-height: 30rem; overflow: hidden; background: #0b0b0c; color: var(--paper); font-family: var(--body); -webkit-font-smoothing: antialiased; line-height: normal; }')
    assert 'isolation: isolate' in css, 'the .azur rule changed in the prototype CSS'
    # the theme squares every corner (border-radius: 0 !important on *); the room keeps its own shapes
    css = re.sub(r'border-radius:\s*([^;}!]+?)\s*(;|\})', r'border-radius: \1 !important\2', css)
    # theme base styles that would change the room: images are display:block/height:auto there
    css += '\n/* ------------------------------------------------------------------ inside the Shopify theme */\n'
    css += '.azur img, .azur-mag img, .azur-pdp img, .azur-holo img { max-width: none; }\n'
    css += '.azur .azur-canvas, .azur .azur-snap { max-width: none; }\n'
    css += '.azur-sr, .azur-cart { display: none !important; }\n'
    write('assets/azur-room.css', '/* AZUR room (generated by azur/tools/build_theme.py from azur/prototype/css/azur-room.css; edit there). */\n' + css)


def build_data():
    v = f'assets/{SET}/views/'
    views = json.load(open(os.path.join(SRC, v, 'views.json')))
    passes = json.load(open(os.path.join(PUB, v, 'passes.json')))           # the published copy carries "_lo"
    mp = os.path.join(PUB, f'assets/{SET}/moves/moves.json')
    moves = json.load(open(mp)) if os.path.exists(mp) else {}
    slim = {}
    for name, m in moves.items():
        keep = {k: m[k] for k in ('frames', 'fps', 'res', 'variants', 'atlas', 'from_', 'to', 'kind') if k in m}
        if m.get('track'): keep['track'] = [{'slots': m['track'][-1].get('slots')}]   # a pulled garment's final place
        slim[name] = keep
    data = {v + 'views.json': views, v + 'passes.json': passes, f'assets/{SET}/moves/moves.json': slim}
    text = json.dumps(data, separators=(',', ':'))
    write('snippets/azur-room-data.liquid', '{%- comment -%} generated by azur/tools/build_theme.py {%- endcomment -%}\n' + text)
    return data


def build_files():
    """Renders for Content > Files: (filename, public source URL). Views and models come from the repo, the half-size
    copies and move strips from theme/files (built by build_artifact.py, committed with the theme)."""
    out = []
    for sub in ('views', 'models'):
        for dp, _, fs in os.walk(os.path.join(SRC, f'assets/{SET}/{sub}')):
            for f in sorted(fs):
                if f.endswith('.json'): continue
                rel = os.path.relpath(os.path.join(dp, f), SRC)
                out.append((files_name(rel), RAW + 'azur/prototype/' + rel))
    lo_root = os.path.join(PUB, f'assets/{SET}/views')
    for dp, _, fs in os.walk(lo_root):
        if os.path.basename(dp) != 'lo': continue
        for f in sorted(fs):
            rel = os.path.relpath(os.path.join(dp, f), PUB)                 # assets/scene3/views/<view>/lo/<pass>.webp
            dst = os.path.join(OUT, 'files', os.path.relpath(rel, f'assets/{SET}'))
            os.makedirs(os.path.dirname(dst), exist_ok=True); shutil.copy2(os.path.join(PUB, rel), dst)
            out.append((files_name(rel), RAW + 'azur/' + os.path.relpath(dst, ROOT)))
    strips = os.path.join(PUB, f'assets/{SET}/moves')
    for dp, _, fs in os.walk(strips):
        for f in sorted(fs):
            if not f.endswith('.webp'): continue
            rel = os.path.relpath(os.path.join(dp, f), PUB)                 # assets/scene3/moves/<move>/<strip>
            dst = os.path.join(OUT, 'files', os.path.relpath(rel, f'assets/{SET}'))
            os.makedirs(os.path.dirname(dst), exist_ok=True); shutil.copy2(os.path.join(PUB, rel), dst)
            out.append((files_name(rel), RAW + 'azur/' + os.path.relpath(dst, ROOT)))
    for rel in ('assets/mag/cover.webp', 'assets/mag/story.webp', 'assets/scene2/outside/bolzplatz.mp4', 'assets/scene2/outside/bolzplatz.webm'):
        out.append((files_name(rel), RAW + 'azur/prototype/' + rel))
    from urllib.parse import quote
    out = [(n, quote(u, safe=':/')) for n, u in out]
    json.dump([{'filename': n, 'url': u} for n, u in out], open(os.path.join(OUT, 'files.json'), 'w'), indent=0)
    return out


def fetch_fonts():
    """Martian Mono (variable) and Caveat 500, latin subset, from Google Fonts once; served by Shopify afterwards."""
    want = {'azur-martian-mono.woff2': 'https://fonts.googleapis.com/css2?family=Martian+Mono:wdth,wght@75..112.5,300..600&display=swap',
            'azur-caveat.woff2': 'https://fonts.googleapis.com/css2?family=Caveat:wght@500&display=swap'}
    ua = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36'}
    for name, url in want.items():
        dst = os.path.join(OUT, 'assets', name)
        if os.path.exists(dst): continue
        css = urllib.request.urlopen(urllib.request.Request(url, headers=ua)).read().decode()
        # the block for the plain latin subset (unicode-range starting U+0000-00FF)
        blocks = re.findall(r'/\* latin \*/\s*@font-face \{([^}]*)\}', css)
        src = re.search(r'url\((https://[^)]+\.woff2)\)', blocks[0]).group(1)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        open(dst, 'wb').write(urllib.request.urlopen(urllib.request.Request(src, headers=ua)).read())


def main():
    os.makedirs(OUT, exist_ok=True)
    build_js(); build_css(); build_data(); fetch_fonts()
    files = build_files()
    print(f'theme files in {OUT}; {len(files)} renders for Shopify Files')


if __name__ == '__main__':
    main()
